export enum CountryCode {
AF = "Afghanistan",
AX = "Aland Islands",
AL = "Albania",
DZ = "Algeria",
AS = "American Samoa",
AD = "Andorra",
AO = "Angola",
AI = "Anguilla",
AQ = "Antarctica",
AG = "Antigua And Barbuda",
AR = "Argentina",
AM = "Armenia",
AW = "Aruba",
AU = "Australia",
AT = "Austria",
AZ = "Azerbaijan",
BS = "Bahamas",
BH = "Bahrain",
BD = "Bangladesh",
BB = "Barbados",
BY = "Belarus",
BE = "Belgium",
BZ = "Belize",
BJ = "Benin",
BM = "Bermuda",
BT = "Bhutan",
BO = "Bolivia",
BQ = "Bonaire, Sint Eustatius, Saba",
BA = "Bosnia And Herzegovina",
BW = "Botswana",
BV = "Bouvet Island",
BR = "Brazil",
IO = "British Indian Ocean Territory",
BN = "Brunei Darussalam",
BG = "Bulgaria",
BF = "Burkina Faso",
BI = "Burundi",
KH = "Cambodia",
CM = "Cameroon",
CA = "Canada",
CV = "Cape Verde",
KY = "Cayman Islands",
CF = "Central African Republic",
TD = "Chad",
CL = "Chile",
CN = "China",
CX = "Christmas Island",
CC = "Cocos (Keeling) Islands",
CO = "Colombia",
KM = "Comoros",
CG = "Congo",
CD = "Congo, Democratic Republic of the",
CK = "Cook Islands",
CR = "Costa Rica",
CI = "Cote D'Ivoire",
HR = "Croatia",
CU = "Cuba",
CW = "Curacao",
CY = "Cyprus",
CZ = "Czech Republic",
DK = "Denmark",
DJ = "Djibouti",
DM = "Dominica",
DO = "Dominican Republic",
EC = "Ecuador",
EG = "Egypt",
SV = "El Salvador",
GQ = "Equatorial Guinea",
ER = "Eritrea",
EE = "Estonia",
ET = "Ethiopia",
FK = "Falkland Islands (Malvinas)",
FO = "Faroe Islands",
FJ = "Fiji",
FI = "Finland",
FR = "France",
GF = "French Guiana",
PF = "French Polynesia",
TF = "French Southern Territories",
GA = "Gabon",
GM = "Gambia",
GE = "Georgia",
DE = "Germany",
GH = "Ghana",
GI = "Gibraltar",
GR = "Greece",
GL = "Greenland",
GD = "Grenada",
GP = "Guadeloupe",
GU = "Guam",
GT = "Guatemala",
GG = "Guernsey",
GN = "Guinea",
GW = "Guinea-Bissau",
GY = "Guyana",
HT = "Haiti",
HM = "Heard Island And Mcdonald Islands",
VA = "Holy See (Vatican City State)",
HN = "Honduras",
HK = "Hong Kong",
HU = "Hungary",
IS = "Iceland",
IN = "India",
ID = "Indonesia",
IR = "Iran, Islamic Republic Of",
IQ = "Iraq",
IE = "Ireland",
IM = "Isle Of Man",
IL = "Israel",
IT = "Italy",
JM = "Jamaica",
JP = "Japan",
JE = "Jersey",
JO = "Jordan",
KZ = "Kazakhstan",
KE = "Kenya",
KI = "Kiribati",
KP = "Korea, Democratic People's Republic Of",
KR = "Korea, Republic Of",
KW = "Kuwait",
KG = "Kyrgyzstan",
LA = "Lao People's Democratic Republic",
LV = "Latvia",
LB = "Lebanon",
LS = "Lesotho",
LR = "Liberia",
LY = "Libyan Arab Jamahiriya",
LI = "Liechtenstein",
LT = "Lithuania",
LU = "Luxembourg",
MO = "Macao",
MK = "Macedonia, The Former Yugoslav Republic Of",
MG = "Madagascar",
MW = "Malawi",
MY = "Malaysia",
MV = "Maldives",
ML = "Mali",
MT = "Malta",
MH = "Marshall Islands",
MQ = "Martinique",
MR = "Mauritania",
MU = "Mauritius",
YT = "Mayotte",
MX = "Mexico",
FM = "Micronesia, Federated States Of",
MD = "Moldova, Republic Of",
MC = "Monaco",
MN = "Mongolia",
ME = "Montenegro",
MS = "Montserrat",
MA = "Morocco",
MZ = "Mozambique",
MM = "Myanmar",
NA = "Namibia",
NR = "Nauru",
NP = "Nepal",
NL = "Netherlands",
NC = "New Caledonia",
NZ = "New Zealand",
NI = "Nicaragua",
NE = "Niger",
NG = "Nigeria",
NU = "Niue",
NF = "Norfolk Island",
MP = "Northern Mariana Islands",
NO = "Norway",
OM = "Oman",
PK = "Pakistan",
PW = "Palau",
PS = "Palestinian Territory, Occupied",
PA = "Panama",
PG = "Papua New Guinea",
PY = "Paraguay",
PE = "Peru",
PH = "Philippines",
PN = "Pitcairn",
PL = "Poland",
PT = "Portugal",
PR = "Puerto Rico",
QA = "Qatar",
RE = "Reunion",
RO = "Romania",
RU = "Russian Federation",
RW = "Rwanda",
BL = "Saint Barthelemy",
SH = "Saint Helena, Ascension And Tristan Da Cunha",
KN = "Saint Kitts And Nevis",
LC = "Saint Lucia",
MF = "Saint Martin",
PM = "Saint Pierre And Miquelon",
VC = "Saint Vincent And The Grenadines",
WS = "Samoa",
SM = "San Marino",
ST = "Sao Tome And Principe",
SA = "Saudi Arabia",
SN = "Senegal",
RS = "Serbia",
SC = "Seychelles",
SL = "Sierra Leone",
SG = "Singapore",
SX = "Sint Maarten",
SK = "Slovakia",
SI = "Slovenia",
SB = "Solomon Islands",
SO = "Somalia",
ZA = "South Africa",
GS = "South Georgia And The South Sandwich Islands",
SS = "South Sudan",
ES = "Spain",
LK = "Sri Lanka",
SD = "Sudan",
SR = "Suriname",
SJ = "Svalbard And Jan Mayen",
SZ = "Swaziland",
SE = "Sweden",
CH = "Switzerland",
SY = "Syrian Arab Republic",
TW = "Taiwan, Province Of China",
TJ = "Tajikistan",
TZ = "Tanzania, United Republic Of",
TH = "Thailand",
TL = "Timor-Leste",
TG = "Togo",
TK = "Tokelau",
TO = "Tonga",
TT = "Trinidad And Tobago",
TN = "Tunisia",
TR = "Turkey",
TM = "Turkmenistan",
TC = "Turks And Caicos Islands",
TV = "Tuvalu",
UG = "Uganda",
UA = "Ukraine",
AE = "United Arab Emirates",
GB = "United Kingdom",
US = "United States",
UM = "United States Outlying Islands",
UY = "Uruguay",
UZ = "Uzbekistan",
VU = "Vanuatu",
VE = "Venezuela, Bolivarian Republic Of",
VN = "Viet Nam",
VG = "Virgin Islands, British",
VI = "Virgin Islands, U.S.",
WF = "Wallis And Futuna",
EH = "Western Sahara",
YE = "Yemen",
ZM = "Zambia",
ZW = "Zimbabwe",
}

// const languages = [
//   { label: "Abkhaz", value: "ab" },
//   { label: "Afar", value: "aa" },
//   { label: "Afrikaans", value: "af" },
//   { label: "Akan", value: "ak" },
//   { label: "Albanian", value: "sq" },
//   { label: "Amharic", value: "am" },
//   { label: "Arabic", value: "ar" },
//   { label: "Aragonese", value: "an" },
//   { label: "Armenian", value: "hy" },
//   { label: "Assamese", value: "as" },
//   { label: "Avaric", value: "av" },
//   { label: "Avestan", value: "ae" },
//   { label: "Aymara", value: "ay" },
//   { label: "Azerbaijani", value: "az" },

//   { label: "Bambara", value: "bm" },
//   { label: "Bashkir", value: "ba" },
//   { label: "Basque", value: "eu" },
//   { label: "Belarusian", value: "be" },
//   { label: "Bengali", value: "bn" },
//   { label: "Bihari", value: "bh" },
//   { label: "Bislama", value: "bi" },
//   { label: "Bosnian", value: "bs" },
//   { label: "Breton", value: "br" },
//   { label: "Bulgarian", value: "bg" },
//   { label: "Burmese", value: "my" },

//   { label: "Catalan", value: "ca" },
//   { label: "Chamorro", value: "ch" },
//   { label: "Chechen", value: "ce" },
//   { label: "Chichewa", value: "ny" },
//   { label: "Chinese", value: "zh" },
//   { label: "Chuvash", value: "cv" },
//   { label: "Cornish", value: "kw" },
//   { label: "Corsican", value: "co" },
//   { label: "Cree", value: "cr" },
//   { label: "Croatian", value: "hr" },
//   { label: "Czech", value: "cs" },

//   { label: "Danish", value: "da" },
//   { label: "Divehi", value: "dv" },
//   { label: "Dutch", value: "nl" },
//   { label: "Dzongkha", value: "dz" },

//   { label: "English", value: "en" },
//   { label: "Esperanto", value: "eo" },
//   { label: "Estonian", value: "et" },
//   { label: "Ewe", value: "ee" },

//   { label: "Faroese", value: "fo" },
//   { label: "Fijian", value: "fj" },
//   { label: "Finnish", value: "fi" },
//   { label: "French", value: "fr" },
//   { label: "Fula", value: "ff" },

//   { label: "Galician", value: "gl" },
//   { label: "Georgian", value: "ka" },
//   { label: "German", value: "de" },
//   { label: "Greek", value: "el" },
//   { label: "Guaraní", value: "gn" },
//   { label: "Gujarati", value: "gu" },

//   { label: "Haitian Creole", value: "ht" },
//   { label: "Hausa", value: "ha" },
//   { label: "Hebrew", value: "he" },
//   { label: "Herero", value: "hz" },
//   { label: "Hindi", value: "hi" },
//   { label: "Hiri Motu", value: "ho" },
//   { label: "Hungarian", value: "hu" },

//   { label: "Icelandic", value: "is" },
//   { label: "Ido", value: "io" },
//   { label: "Igbo", value: "ig" },
//   { label: "Indonesian", value: "id" },
//   { label: "Interlingua", value: "ia" },
//   { label: "Interlingue", value: "ie" },
//   { label: "Inuktitut", value: "iu" },
//   { label: "Inupiaq", value: "ik" },
//   { label: "Irish", value: "ga" },
//   { label: "Italian", value: "it" },

//   { label: "Japanese", value: "ja" },
//   { label: "Javanese", value: "jv" },

//   { label: "Kannada", value: "kn" },
//   { label: "Kanuri", value: "kr" },
//   { label: "Kashmiri", value: "ks" },
//   { label: "Kazakh", value: "kk" },
//   { label: "Khmer", value: "km" },
//   { label: "Kikuyu", value: "ki" },
//   { label: "Kinyarwanda", value: "rw" },
//   { label: "Komi", value: "kv" },
//   { label: "Kongo", value: "kg" },
//   { label: "Korean", value: "ko" },
//   { label: "Kurdish", value: "ku" },
//   { label: "Kwanyama", value: "kj" },

//   { label: "Lao", value: "lo" },
//   { label: "Latin", value: "la" },
//   { label: "Latvian", value: "lv" },
//   { label: "Limburgish", value: "li" },
//   { label: "Lingala", value: "ln" },
//   { label: "Lithuanian", value: "lt" },
//   { label: "Luba-Katanga", value: "lu" },
//   { label: "Luxembourgish", value: "lb" },

//   { label: "Macedonian", value: "mk" },
//   { label: "Malagasy", value: "mg" },
//   { label: "Malay", value: "ms" },
//   { label: "Malayalam", value: "ml" },
//   { label: "Maltese", value: "mt" },
//   { label: "Manx", value: "gv" },
//   { label: "Maori", value: "mi" },
//   { label: "Marathi", value: "mr" },
//   { label: "Marshallese", value: "mh" },
//   { label: "Mongolian", value: "mn" },

//   { label: "Nauru", value: "na" },
//   { label: "Navajo", value: "nv" },
//   { label: "Ndonga", value: "ng" },
//   { label: "Nepali", value: "ne" },
//   { label: "North Ndebele", value: "nd" },
//   { label: "Northern Sami", value: "se" },
//   { label: "Norwegian", value: "no" },
//   { label: "Norwegian Bokmål", value: "nb" },
//   { label: "Norwegian Nynorsk", value: "nn" },

//   { label: "Occitan", value: "oc" },
//   { label: "Ojibwe", value: "oj" },
//   { label: "Odia", value: "or" },
//   { label: "Oromo", value: "om" },
//   { label: "Ossetian", value: "os" },

//   { label: "Panjabi", value: "pa" },
//   { label: "Pāli", value: "pi" },
//   { label: "Persian", value: "fa" },
//   { label: "Polish", value: "pl" },
//   { label: "Portuguese", value: "pt" },
//   { label: "Pashto", value: "ps" },

//   { label: "Quechua", value: "qu" },

//   { label: "Romanian", value: "ro" },
//   { label: "Romansh", value: "rm" },
//   { label: "Russian", value: "ru" },

//   { label: "Samoan", value: "sm" },
//   { label: "Sango", value: "sg" },
//   { label: "Sanskrit", value: "sa" },
//   { label: "Sardinian", value: "sc" },
//   { label: "Scottish Gaelic", value: "gd" },
//   { label: "Serbian", value: "sr" },
//   { label: "Shona", value: "sn" },
//   { label: "Sindhi", value: "sd" },
//   { label: "Sinhala", value: "si" },
//   { label: "Slovak", value: "sk" },
//   { label: "Slovenian", value: "sl" },
//   { label: "Somali", value: "so" },
//   { label: "South Ndebele", value: "nr" },
//   { label: "Southern Sotho", value: "st" },
//   { label: "Spanish", value: "es" },
//   { label: "Sundanese", value: "su" },
//   { label: "Swahili", value: "sw" },
//   { label: "Swati", value: "ss" },
//   { label: "Swedish", value: "sv" },

//   { label: "Tagalog", value: "tl" },
//   { label: "Tahitian", value: "ty" },
//   { label: "Tajik", value: "tg" },
//   { label: "Tamil", value: "ta" },
//   { label: "Tatar", value: "tt" },
//   { label: "Telugu", value: "te" },
//   { label: "Thai", value: "th" },
//   { label: "Tibetan", value: "bo" },
//   { label: "Tigrinya", value: "ti" },
//   { label: "Tongan", value: "to" },
//   { label: "Tsonga", value: "ts" },
//   { label: "Tswana", value: "tn" },
//   { label: "Turkish", value: "tr" },
//   { label: "Turkmen", value: "tk" },
//   { label: "Twi", value: "tw" },

//   { label: "Ukrainian", value: "uk" },
//   { label: "Urdu", value: "ur" },
//   { label: "Uyghur", value: "ug" },
//   { label: "Uzbek", value: "uz" },

//   { label: "Venda", value: "ve" },
//   { label: "Vietnamese", value: "vi" },
//   { label: "Volapük", value: "vo" },

//   { label: "Walloon", value: "wa" },
//   { label: "Welsh", value: "cy" },
//   { label: "Western Frisian", value: "fy" },

//   { label: "Wolof", value: "wo" },

//   { label: "Xhosa", value: "xh" },

//   { label: "Yiddish", value: "yi" },
//   { label: "Yoruba", value: "yo" },

//   { label: "Zhuang", value: "za" },
//   { label: "Zulu", value: "zu" }
// ] as const;

export enum Languages {
  ab = "Abkhaz",
  aa = "Afar",
  af = "Afrikaans",
  ak = "Akan",
  sq = "Albanian",
  am = "Amharic",
  ar = "Arabic",
  an = "Aragonese",
  hy = "Armenian",
  as = "Assamese",
  av = "Avaric",
  ae = "Avestan",
  ay = "Aymara",
  az = "Azerbaijani",

  bm = "Bambara",
  ba = "Bashkir",
  eu = "Basque",
  be = "Belarusian",
  bn = "Bengali",
  bh = "Bihari",
  bi = "Bislama",
  bs = "Bosnian",
  br = "Breton",
  bg = "Bulgarian",
  my = "Burmese",

  ca = "Catalan",
  ch = "Chamorro",
  ce = "Chechen",
  ny = "Chichewa",
  zh = "Chinese",
  cv = "Chuvash",
  kw = "Cornish",
  co = "Corsican",
  cr = "Cree",
  hr = "Croatian",
  cs = "Czech",

  da = "Danish",
  dv = "Divehi",
  nl = "Dutch",
  dz = "Dzongkha",

  en = "English",
  eo = "Esperanto",
  et = "Estonian",
  ee = "Ewe",

  fo = "Faroese",
  fj = "Fijian",
  fi = "Finnish",
  fr = "French",
  ff = "Fula",

  gl = "Galician",
  ka = "Georgian",
  de = "German",
  el = "Greek",
  gn = "Guaraní",
  gu = "Gujarati",

  ht = "Haitian Creole",
  ha = "Hausa",
  he = "Hebrew",
  hz = "Herero",
  hi = "Hindi",
  ho = "Hiri Motu",
  hu = "Hungarian",

  is = "Icelandic",
  io = "Ido",
  ig = "Igbo",
  id = "Indonesian",
  ia = "Interlingua",
  ie = "Interlingue",
  iu = "Inuktitut",
  ik = "Inupiaq",
  ga = "Irish",
  it = "Italian",

  ja = "Japanese",
  jv = "Javanese",

  kn = "Kannada",
  kr = "Kanuri",
  ks = "Kashmiri",
  kk = "Kazakh",
  km = "Khmer",
  ki = "Kikuyu",
  rw = "Kinyarwanda",
  kv = "Komi",
  kg = "Kongo",
  ko = "Korean",
  ku = "Kurdish",
  kj = "Kwanyama",

  lo = "Lao",
  la = "Latin",
  lv = "Latvian",
  li = "Limburgish",
  ln = "Lingala",
  lt = "Lithuanian",
  lu = "Luba-Katanga",
  lb = "Luxembourgish",

  mk = "Macedonian",
  mg = "Malagasy",
  ms = "Malay",
  ml = "Malayalam",
  mt = "Maltese",
  gv = "Manx",
  mi = "Maori",
  mr = "Marathi",
  mh = "Marshallese",
  mn = "Mongolian",

  na = "Nauru",
  nv = "Navajo",
  ng = "Ndonga",
  ne = "Nepali",
  nd = "North Ndebele",
  se = "Northern Sami",
  no = "Norwegian",
  nb = "Norwegian Bokmål",
  nn = "Norwegian Nynorsk",

  oc = "Occitan",
  oj = "Ojibwe",
  or = "Odia",
  om = "Oromo",
  os = "Ossetian",

  pa = "Panjabi",
  pi = "Pāli",
  fa = "Persian",
  pl = "Polish",
  pt = "Portuguese",
  ps = "Pashto",

  qu = "Quechua",

  ro = "Romanian",
  rm = "Romansh",
  ru = "Russian",

  sm = "Samoan",
  sg = "Sango",
  sa = "Sanskrit",
  sc = "Sardinian",
  gd = "Scottish Gaelic",
  sr = "Serbian",
  sn = "Shona",
  sd = "Sindhi",
  si = "Sinhala",
  sk = "Slovak",
  sl = "Slovenian",
  so = "Somali",
  nr = "South Ndebele",
  st = "Southern Sotho",
  es = "Spanish",
  su = "Sundanese",
  sw = "Swahili",
  ss = "Swati",
  sv = "Swedish",

  tl = "Tagalog",
  ty = "Tahitian",
  tg = "Tajik",
  ta = "Tamil",
  tt = "Tatar",
  te = "Telugu",
  th = "Thai",
  bo = "Tibetan",
  ti = "Tigrinya",
  to = "Tongan",
  ts = "Tsonga",
  tn = "Tswana",
  tr = "Turkish",
  tk = "Turkmen",
  tw = "Twi",

  uk = "Ukrainian",
  ur = "Urdu",
  ug = "Uyghur",
  uz = "Uzbek",

  ve = "Venda",
  vi = "Vietnamese",
  vo = "Volapük",

  wa = "Walloon",
  cy = "Welsh",
  fy = "Western Frisian",

  wo = "Wolof",

  xh = "Xhosa",

  yi = "Yiddish",
  yo = "Yoruba",

  za = "Zhuang",
  zu = "Zulu",
}